#!/bin/bash
echo "Programme werden nun installiert"

#---snap---#
sudo apt update
sudo snap install spotify 
sudo snap install atom --classic
sudo snap install libreoffice 
sudo snap install telegram-desktop 
sudo snap install signal-desktop 
sudo snap install --classic riseup-vpn
sudo snap install keepassxc
#sudo snap install android -studio --classic
#sudo snap install flutter --classic

#---apt---#
sudo add-apt-repository ppa:unit193/encryption 
sudo add-apt-repository ppa:sebastian-stenzel/cryptomator
sudo apt update 
sudo apt install veracrypt 
sudo apt install cryptomator
sudo apt install nextcloud-desktop  
sudo apt install clamtk 
sudo apt install clamtk-nautilus 
sudo apt install clamtk-unofficial-sigs 
sudo apt install grsync 
sudo apt install gnome-mahjongg 
sudo apt install virtualbox virtualbox-qt virtualbox-dkms 
sudo apt install gnome-tweaks
sudo apt install usb-creator-gtk
sudo apt install virtualbox-guest-additions-iso 
sudo apt install pdfarranger 
sudo apt install vlc 
sudo apt install rmlint 
sudo apt install neofetch 
sudo apt install cmatrix
sudo apt install hollywood 
sudo apt install gnome-screenshot
sudo apt install soundconverter
sudo apt install audacious
sudo apt install glances
sudo apt install hardinfo 

sudo apt update
sudo apt upgrade 
sudo apt dist-upgrade 
sudo apt autoremove 
sudo apt autoclean 
sudo apt clean 

echo "Alle Programme installiert (Ausnahme: Google Chrome, USB-Guard, Freetube, Soundconverter, Signal, Flutter, VS Code)"
