#!/bin/bash
echo "Programme werden nun installiert"

#---snap---#
sudo apt-get update
sudo snap install spotify 
sudo snap install atom --classic
sudo snap install libreoffice 
sudo snap install telegram-desktop 
sudo snap install signal-desktop 
sudo snap install --classic riseup-vpn
sudo snap install keepassxc
sudo snap install joplin
#sudo snap install android -studio --classic
#sudo snap install flutter --classic

#---apt---#
sudo add-apt-repository ppa:unit193/encryption 
sudo add-apt-repository ppa:sebastian-stenzel/cryptomator
sudo apt update 
sudo apt install veracrypt 
sudo apt install cryptomator
sudo apt install nextcloud-desktop  
sudo apt-get install clamtk 
sudo apt-get install clamtk-nautilus 
sudo apt-get install clamtk-unofficial-sigs 
sudo apt-get install grsync 
sudo apt-get install gnome-mahjongg 
sudo apt-get install virtualbox virtualbox-qt virtualbox-dkms 
sudo apt install gnome-tweaks
sudo apt-get install usb-creator-gtk 
sudo apt-get install virtualbox-guest-additions-iso 
sudo apt-get install pdfarranger 
sudo apt-get install vlc 
sudo apt-get install rmlint 
sudo apt-get install neofetch 
sudo apt-get install cmatrix
sudo apt install hollywood 
sudo apt install gnome-screenshot
sudo apt-get install soundconverter
sudo apt-get install audacious
sudo apt-get install glances
#sudo apt-get install hardinfo 

sudo apt-get update
sudo apt-get upgrade 
sudo apt-get dist-upgrade 
sudo apt autoremove 
sudo apt autoclean 
sudo apt clean 

echo "Alle Programme installiert (Ausnahme: Google Chrome, USB-Guard, Freetube, Soundconverter, Signal, Flutter, VS Code)"
